web/src/lib/components/admin/Accordion.svelte
web/src/lib/components/admin/MenuItem.svelte
web/src/lib/components/admin/MobileMenu.svelte
web/src/lib/components/admin/Sidebar.svelte
web/src/routes/(admin)/+layout.svelte

Create mobile navigation

---

docs/schema_objectives.md
flake.nix
sdk/.gitignore
sdk/nodemon.json
sdk/package.json
sdk/pnpm-lock.yaml
sdk/pnpm-workspace.yaml
sdk/tsconfig.json
sdk/tsconfig.prod.json
sdk/vitest.config.ts

feat(sdk): Initial setup

---

landing/src/lib/components/ProblemSection.svelte

> [!warning] 
> Please do not merge, this is going to be used as the CI demonstration

feat: Added border for card in ProblemSection.svelte

---

web/src/app.css
web/src/lib/components/admin/Dropzone.svelte
web/src/lib/components/admin/media/MediaCard.svelte
web/src/routes/(admin)/collections/[collectionSlug]/[resourceSlug]/+page.svelte
web/src/routes/(admin)/collections/media/+page.svelte

feat: upload components

---

api/internal/auth/auth.go
api/internal/collection/collection.go
api/internal/media/handler.go
api/internal/util/json.go
api/main.go
web/src/routes/(admin)/collections/[collectionSlug]/+page.server.ts
web/src/routes/(auth)/login/+page.server.ts

Add JSON encoding / decoding helper methods

---

flux/apps/cms/api/deployment.yaml

Setup postgres in production

---

api/internal/util/middleware.go
api/main.go

Add middleware utility function

---

api/migrations/10_add_globals.yaml
sdk/src/collection.ts
sdk/src/registry.ts

feat: Add support for global collections

---

api/README.md
api/internal/migrations/migrations.go
api/internal/migrations/migrations_test.go
api/main.go
web/src/hooks.server.ts
web/src/routes/password/+layout.server.ts

Split pgroll state schemas

---

api/main.go

fix: Fixed listening port for the program

---

landing/mimsy.schema.json
landing/package.json
landing/src/lib/collections.ts
pnpm-lock.yaml
sdk/src/fields.ts

feat: Added collections and updated schema

---

.gitignore
api/internal/collection/collection_test.go
api/internal/collection/query.go
api/internal/collection/repository.go
api/internal/sync/migrate.go
api/internal/sync/repository.go
api/internal/sync/service.go
api/justfile
api/main.go
api/migrations/13_add_skipped.yaml
api/pkg/mimsy_schema/schema.go
web/src/lib/types/sync.ts
web/src/routes/(admin)/sync/+page.svelte

feat: Skip on schema not changed

---

api/internal/sync/migrate.go

fix: Added debug logging

---

api/internal/sync/service.go
web/src/routes/(admin)/sync/+page.svelte

feat: Enable collections push

---

landing/mimsy.schema.json
landing/src/lib/collections.ts

test: Added new field in collection

---

api/go.mod
api/pkg/schema_generator/json_marshal.go
api/pkg/schema_generator/schema_test.go

feat: Ensured that marshall + unmarshalling of schema works

---

api/internal/collection/collection_test.go
api/internal/collection/repository.go
api/internal/collection/response.go
api/migrations/15_remove_user_fk.yaml
web/src/routes/(admin)/collections/[collectionSlug]/+page.svelte

Remove user reference from collection

---

cli/package.json
cli/src/commands/update.ts
cli/src/utils/locate.ts
cli/tests/cli.integration.test.ts
cli/tests/commands/update.test.ts
sdk/package.json

fix: Fixed cli setup, now finds the project more intelligently

---

cli/src/commands/init.ts
cli/tests/utils/test-helpers.ts

feat: Improved init command

---

landing/mimsy.schema.json

fix: Rename column

---

api/internal/util/request.go
api/main.go

feat: add http request logger middleware

---

web/src/hooks.server.ts

fix: fix auth user fetching

---

docs/devops.md

Devops doc

---

api/pkg/schema_diff/diff.go
flux/apps/slides-demo/deployment.yaml
flux/apps/slides-demo/image-policy.yaml
flux/apps/slides-demo/image-repository.yaml
flux/apps/slides-demo/ingress.yaml
flux/apps/slides-demo/kustomization.yaml
flux/apps/slides-demo/service.yaml
flux/base/apps.yaml

Closes #329\nDeploys [slides-demo](https://github.com/mimsy-cms/slides-demo) to the cluster

chore(deployment): Added deployment for the slides demo
